language: node_js
node_js:
- node
cache:
  directories:
  - "${HOME}/.cache/yarn"
  - node_modules
notifications:
  email:
    on_failure: always
    on_success: never
before_install:
- yarn config set progress=false
before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.email "travis@travis-ci.org"
- git branch
- standard-version
- git branch
- bash test.sh
- git push --follow-tags -q https://github.com/MatthewMi11er/testrepo HEAD:master
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ONyLYQzv7k3+oX/98cg6ds8dWWv+bjE8QWsNNFQM4y98WchmJnKvMK2bhSb8ceIdIk3S4tXDFJtWj1eah/Dt/GZMzUgBe9t+HE0svqDFUddSzHdxH/VXq/D6woe26xjSGPP1RLU9/z7XcBiIYHkmJq+iGCEjUkib9pzdCBzm1vhocpogdQlAkOMJuHSqUBdtt5m66jtaYCDfPnJRfspJUJ9L26Jp+26ePwZMpLUJ/aGpbSirVtQyvrYDXhNleQmZLtKFxgK6GVVXIrPnLLZtbV6OEiMaheG+EKL4Ey8zmQhrVsFbjlKbmdrZomE1damujXzmqTEP7IlZnQkJFZyHuwB6v16Z6LyFWVUBXUlFDy2x6f17pCQw7wTgrIGDcIa6mi+9/hDacKu2jq++ABAA7dV4rqdx6N9ekCZqBM1jtev9EV8SDHgeVuKnnzW9S8pltiyT+tvx7nEcXTqc6cYxVjDXmR2/ild+cRPobQQTrfS2R+AlSwsMzLfCAU2Kx689F/Kq71s9x/9IOIUlhB9jGlDekTdAYYrZSsgFXdEr+XGP6xoKhGWLO0M6v0ZeyAirdOkMMuUMbDF24GTc2/fjRc5ZGrEvyMthep+iVF9y9KaySNI/oWxfQhMzkeTGhsfZDNs6bhM1gxbqOuPP6ub+fkHRffFujVRbg084AyY/gt4=
  on:
    branch: master
    repo: MatthewMi11er/testrepo
